### ISSUE TITLE
Duda sobre nueva implementación de "insert"

### ISSUE THREAD

**Issue by MortizDX** [PUC-IIC3141/2018-1#1]
Ando un poco (bueno, bastante XD) perdido sobre como debe quedar la nueva implementación de "insert" con las tuplas de largo variable. Como antes los offsets estaban definidos cuando se creaba una tabla, solo requerían el dato a ingresar, ya que conocían la posición actual que les correspondía ir, por lo que no se preocupaban de "cuando" se haría la inserción o no (ya tenían un puesto reservado, si es que entiendo correctamente).

Como no he encontrado desde que otro paquete llama a ese tipo de método (los setInt y setString), y que ahora en donde irá cada dato de una tupla dependerá de un valor vecino anterior (si era de largo variable), mi duda es más bien como se realiza una inserción de tupla, o al menos saber que otro paquete de simpledb se encarga de insertar tuplas como tal, puesto que no estoy seguro si en alguna parte se tienen todos los datos en secuencia de la nueva tupla a ingresar y de esa secuencia se llaman consecutivamente los "sets" correspodientes, o si acaso nosotros debemos encargarnos de todo ese proceso.

**Comment by cirojas** [comment]
Si buscas que clases usan a `RecordPage` (recordar usar el shortcut ctrl+shift+G teniendo el cursor sobre la clase/método/atributo para ver donde se usa) verás que solo es utilizado solo por `RecordFile` y `ChunkScan` (por ahora ignoraremos a `ChunkScan` porque como está simpleDB hasta ahora nunca se usa). Las clases que ocupan a `RecordFile` cuando quieren insertar una tupla llamarán a `insert()` y luego por cada atributo del esquema llamarán a `setInt(fieldName, value)` o  `setString(fieldName, value)`, un ejemplo de esto lo puedes ver en la clase `IndexMgr`, en el método `createIndex`:
```
RecordFile rf = new RecordFile(ti, tx);
rf.insert();
rf.setString("indexname", idxname);
rf.setString("tablename", tblname);
rf.setString("fieldname", fldname);
rf.close();
```
Notese que no debe importar el orden en que se setean los atributos, ya que en `TableInfo` está la información del orden de los atributos del schema. Hint: Podría ser útil cambiar el comportamiento del método `offset(fieldName)` de la clase `TableInfo`.

**Comment by MortizDX** [comment]
Muchas gracias! No sé porqué no se me había ocurrido buscar el "insert" mismo y no los "sets", jaja. Pero si quiero probar insertar tuplas como tal, ¿sólo se puede desde el sqlinterpreter?

**Comment by cirojas** [comment]
No es necesario usar el SqlInterpreter, aunque deben asegurarse que en su implementación este siga funcionando. Para tus test te recomiento basarte en las clases de ejemplo `CreateStudentDB` y `StudentMajorNoServer` y ejecutar las consultas directamente desde el código. Incluso puedes ir más allá y llamar a los métodos directamente (sin consulta SQL). Para testear la inserción yo haría algo así:
 
```
public static void main(String[] args) {
		
	// Se inicia la BD, si no existe la crea, sino recupera lo existente
	String dbName = "ExampleSimpleDB";
	SimpleDB.init(dbName);
				
	// Se crea el schema con 2 campos: field1(int) y field2(varchar(15))
	Schema schema = new Schema();
	schema.addIntField("field1");
	schema.addStringField("field2", 15);

	/* Creamos la transacion, en simpleDB toda operacion de escritura o lectura 
	 * necesita una transaccion. */
	Transaction tx = new Transaction();
		
	// Se crea la tabla la tabla
	MetadataMgr metadataMgr = SimpleDB.mdMgr();
	String tableName = "table1";
	metadataMgr.createTable(tableName, schema, tx);
		
	tx.commit();
		
	// Creamos otra transaccion para insertar datos
	tx = new Transaction();
	
	TableInfo ti = new TableInfo(tableName, schema);
	
	RecordFile rf = new RecordFile(ti, tx);
	rf.insert();
	rf.setInt("field1", 1);
	rf.setString("field2", "Hola Mundo");
	rf.close();
	
	tx.commit();
}
```

**Comment by MortizDX** [comment]
Sé que es bien tarde pero olvidé responder en su momento. Me fue útil lo que respondiste, muchas gracias!
