### ISSUE TITLE
Caso Update de atributo de largo variable

### ISSUE THREAD

**Issue by fdoflorenzano** [PUC-IIC3141/2018-1#3]
Hola. Tengo la duda si debiésemos cubrir el caso en que se actualice un `String` de una tupla ya insertada previamente. Pregunto ya que la solución en la literatura es usar una overflow page y el enunciado dice que no debemos implementarlas, además de que dada la arquitectura y comportamiento de los métodos de `RecordPage `y `RecordFile`, es un poco tedioso y engorroso mover una tupla completa de lugar.

Saludos y gracias.

**Comment by cirojas** [comment]
La idea es que si lo hagan. Una forma simple es borrar la tupla de la página e insertarla en otra. 

> es un poco tedioso y engorroso mover una tupla completa de lugar.

No debiese ser muy complicado hacerlo desde `RecordFile`, te recomiento cambiar el tipo de retorno del método `setString` de la clase RecordPage.

**Comment by fdoflorenzano** [comment]
Sí, eso pensaba hacer. Gracias.

**Comment by cirojas** [comment]
> Entonces, tenemos que también chequear, cuando llaman a "setString", el largo del nuevo string siempre?

Exacto. Debes majejar todos los posibles casos al llamar setString:
1. No se había seteado previamente el string y el nuevo string cabe en la página.
2. Se había seteado previamente un string y el nuevo es de igual tamaño o más corto
3. Se había seteado previamente un string, el nuevo es de mayor tamaño y hay espacio en la página.
4. No se habia seteado previamente el string y el nuevo string no cabe en la página  (el record se debe sacar de la página e insertar en otra).
5. Se había seteado previamente un string, el nuevo es de mayor tamaño y no hay espacio en la página (el record se debe sacar de la página e insertar en otra).

Recomiendo ir implementando los casos de forma incremental, en el mismo orden que los enumere.
