### ISSUE TITLE
Manejo de nulos

### ISSUE THREAD

**Issue by fdoflorenzano** [PUC-IIC3141/2018-1#9]
Hola, 

Tengo la duda sobre el manejo de nulos, en particular, lo que me complica es como devolver el valor de nulo al resto del proyecto sin que haga conflictos en todo. En particular, como devolver null a un getInt, por ejemplo. No puedo devolver 'null' por la firma del método y al intentar usar null de Java me ha tirado varios errores, tal vez hay una mejor forma de trabajar con ellos.

¿Alguna recomendación?

**Comment by cirojas** [comment]
puedes cambiar la firma de los métodos para que en vez de devolver un int devuelvan un objeto Integer, que si permite nulos.

**Comment by fdoflorenzano** [comment]
¡Gracias!
